id: bw-amr-ig
name: BW-AMR-IG
title: "Botswana AMR Implementation Guide"
status: draft
version: 0.1.0
canonical: http://bw.health.gov/fhir/ImplementationGuide/bw-amr-ig
fhirVersion: 4.3.0
copyrightYear: 2025
releaseLabel: "0.1.0"
description: "FHIR Implementation Guide for the Botswana AMR Data Analytics Platform"
publisher:
  name: "University of Botswana Partnership"
  url: "https://github.com/Dokotela/bw-amr-ig"
parameters:
  show-inherited-invariants: false
  usage-stats-opt-out: false
menu:
  Home: index.html
  Background: background.html
  Use Cases: use-cases.html
  Implementation: implementation.html
  Artifacts: artifacts.html
