import 'package:fhir_r4/fhir_r4.dart' show ValueSet;

/// http://bw.health.gov/fhir/amr/ValueSet/botswana-amr-interpretation
/// (no version), from
/// fsh-generated/resources/ValueSet-botswana-amr-interpretation.json.
/// Generated by tool/generate_artifacts.dart; do not edit.
final ValueSet botswanaAmrInterpretation = ValueSet.fromJson(
  {
    'resourceType': 'ValueSet',
    'status': 'draft',
    'name': 'BotswanaAMRInterpretation',
    'id': 'botswana-amr-interpretation',
    'title': 'Botswana AMR Interpretation',
    'description': 'Only Susceptible, Intermediate, or Resistant',
    'url': 'http://bw.health.gov/fhir/amr/ValueSet/botswana-amr-interpretation',
    'compose': {
      'include': [
        {
          'system':
              'http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation',
          'concept': [
            {
              'code': 'S',
              'display': 'Susceptible',
            },
            {
              'code': 'I',
              'display': 'Intermediate',
            },
            {
              'code': 'R',
              'display': 'Resistant',
            },
          ],
        },
      ],
    },
  },
);
