import 'package:fhir_r4/fhir_r4.dart' show ValueSet;

/// http://bw.health.gov/fhir/amr/ValueSet/botswana-amr-ward-type-vs
/// (no version), from
/// fsh-generated/resources/ValueSet-botswana-amr-ward-type-vs.json.
/// Generated by tool/generate_artifacts.dart; do not edit.
final ValueSet botswanaAmrWardTypeVs = ValueSet.fromJson(
  {
    'resourceType': 'ValueSet',
    'status': 'draft',
    'name': 'BotswanaAMRWardTypeVS',
    'id': 'botswana-amr-ward-type-vs',
    'title': 'Botswana AMR Ward Type',
    'description':
        'Ward/location types for AMR surveillance, aligned with WHONET '
        'location type and GLASS origin classification',
    'url': 'http://bw.health.gov/fhir/amr/ValueSet/botswana-amr-ward-type-vs',
    'compose': {
      'include': [
        {
          'system': 'http://terminology.hl7.org/CodeSystem/v3-ActCode',
          'concept': [
            {
              'code': 'IMP',
              'display': 'inpatient encounter',
            },
            {
              'code': 'AMB',
              'display': 'ambulatory',
            },
            {
              'code': 'EMER',
              'display': 'emergency',
            },
            {
              'code': 'ACUTE',
              'display': 'inpatient acute',
            },
            {
              'code': 'OBSENC',
              'display': 'observation encounter',
            },
          ],
        },
      ],
    },
  },
);
