/// Writes every CodeSystem and ValueSet under `../fsh-generated/resources`
/// (SUSHI's output, the IG's source of record, tracked in git) as a Dart file
/// under `lib/fhir/`, plus the `fhir.dart` barrel. Run from the package root:
///
/// ```sh
/// dart run tool/generate_artifacts.dart
/// ```
///
/// Replaces the inline Python `json.dumps` in `_genonce.sh` (2026-09-22):
/// the files it produced failed 2,000 lint checks and carried an older
/// canonical URL than `sushi-config.yaml`. It read the publisher's output,
/// which is not tracked and needs a terminology server to build; SUSHI's
/// output carries the same codes and canonical URLs without the narrative.
/// The emitter is the family's shared `DartLiteralWriter` (package
/// dart_literal);
/// `test/` proves each Dart object equals its source.
library;

import 'dart:convert';
import 'dart:io';

import 'package:dart_literal/dart_literal.dart';

/// Where SUSHI writes the IG's resources, relative to this package.
const sourceDir = '../fsh-generated/resources';

bool _isTerminology(String path) {
  final name = path.split('/').last;
  return name.endsWith('.json') &&
      (name.startsWith('CodeSystem-') || name.startsWith('ValueSet-'));
}

/// `ValueSet-botswana-amr-ast-method-vs.json` ->
/// (`value_set_botswana_amr_ast_method_vs`, `botswanaAmrAstMethodVs`).
(String file, String variable) namesFor(String assetName) {
  final stem = assetName.replaceAll('.json', '');
  final dash = stem.indexOf('-');
  final type = stem.substring(0, dash);
  final id = stem.substring(dash + 1);
  final typeSnake = type.replaceAllMapped(
    RegExp('(?<=[a-z])[A-Z]'),
    (m) => '_${m[0]}',
  );
  final file = '${typeSnake}_${id.replaceAll('-', '_')}'.toLowerCase();
  final words = id.split('-');
  final variable =
      words.first +
      words.skip(1).map((w) => w[0].toUpperCase() + w.substring(1)).join();
  return (file, variable);
}

Future<void> main() async {
  final assets =
      Directory(sourceDir)
          .listSync()
          .whereType<File>()
          .where((f) => _isTerminology(f.path))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  if (assets.isEmpty) {
    stderr.writeln(
      'no CodeSystem/ValueSet JSON in $sourceDir: run sushi first',
    );
    exitCode = 66;
    return;
  }
  final outDir = Directory('lib/fhir');
  for (final f in outDir.listSync().whereType<File>()) {
    f.deleteSync();
  }
  final exports = <String>[];
  final all = <String>[];
  for (final asset in assets) {
    final name = asset.uri.pathSegments.last;
    final json = jsonDecode(asset.readAsStringSync()) as Map<String, dynamic>;
    final type = json['resourceType'] as String;
    final (file, variable) = namesFor(name);
    File('${outDir.path}/$file.dart').writeAsStringSync(
      dartFileForJson(
        json: json,
        type: type,
        name: variable,
        comment: [
          '${json['url']}',
          '(${json['version'] ?? 'no version'}), from',
          'fsh-generated/resources/$name.',
          'Generated by tool/generate_artifacts.dart; do not edit.',
        ],
      ),
    );
    exports.add("export '$file.dart';");
    all.add('  $variable,');
    stdout.writeln('$name -> lib/fhir/$file.dart');
  }
  final imports = [
    "import 'package:fhir_r4/fhir_r4.dart' show Resource;",
    for (final e in exports)
      e.replaceFirst("export '", "import 'package:bw_amr_ig/fhir/"),
  ]..sort();
  File('${outDir.path}/fhir.dart').writeAsStringSync(
    '${imports.join('\n')}\n\n'
    '${exports.join('\n')}\n\n'
    '/// Every artifact in this library, for tests and lookups.\n'
    'final List<Resource> all = <Resource>[\n${all.join('\n')}\n];\n',
  );
  final result = await Process.run('dart', ['format', outDir.path]);
  stdout.write(result.stdout);
  stderr.write(result.stderr);
  if (result.exitCode != 0) exitCode = result.exitCode;
}
